# Assuming port forwarding at least one validator node and the kv-store
# key_endpoint="https://kms-dev-v1.s3.eu-west-3.amazonaws.com/threshold/PUB-p3/PublicKey"
s3_endpoint = "/Users/luismontero/Documents/work/zama/kms-core/blockchain/simulator/aws/threshold/"
key_id = "d4d17a412a6533599b010c8ffc3d6ebdc6b1cfad"
key_folder = ["PUB-p1","PUB-p2","PUB-p3","PUB-p4"]
validator_addresses = ["http://localhost:9090"]
http_validator_endpoints = ["http://localhost:36657"]
kv_store_address = "http://localhost:8088"

# TODO: add support for "latest" and automatically get the last contract
# contract-code: 61 this needs to be kept up to date with the k8 cluster
contract = "wasm15nyecjfy9vpg4ry7lkzy56fzeef6uruktdqktr7k5zsuqhfad42skqxvw3"

mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"
faucet_address = "http://localhost:8000"
