s3_endpoint = "http://s3-mock:9000/kms"
object_folder = ["PUB-p1","PUB-p2","PUB-p3","PUB-p4"]

validator_addresses = ["http://kms-blockchain-validator:9090"]
http_validator_endpoints = ["http://kms-blockchain-validator:26657"]
kv_store_address = "http://kms-kv-store:8088"
faucet_address = "http://localhost:8000"

# contract = "wasm1cnuw3f076wgdyahssdkd0g3nr96ckq8cwa2mh029fn5mgf2fmcms9ax00l"
# TODO: update latest option to take latest asc contract and not just latest contract
# contract = "latest"
contract = "wasm1cnuw3f076wgdyahssdkd0g3nr96ckq8cwa2mh029fn5mgf2fmcms9ax00l"
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"
