s3_endpoint = "http://dev-s3-mock:9000/kms"
object_folder = ["PUB-p1","PUB-p2","PUB-p3","PUB-p4"]

validator_addresses = ["http://dev-kms-blockchain-validator:9090"]
http_validator_endpoints = ["http://dev-kms-blockchain-validator:26657"]
kv_store_address = "http://dev-kv-store:8088"
faucet_address = "http://localhost:8000"

# TODO: update latest option to take latest asc contract and not just latest contract
# contract = "latest"
asc_address = "wasm1aakfpghcanxtc45gpqlx8j3rq0zcpyf49qmhm9mdjrfx036h4z5se0hfnq"
mnemonic = "degree fringe genuine soon present soul jelly catch that million van idle ship always silly uphold private mandate great used donate armed shock uphold"

# Address of the CSC
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
