name: zama-kms-gateway

services:
  # 5. Launch key-gen
  # TODO: store gateway config in volume and modify it with key-id
  dev-kms-simulator-keygen:
    image: ghcr.io/zama-ai/kms-blockchain-simulator:${DOCKER_IMAGES_TAG}
    build:
      context: .
      dockerfile: blockchain/simulator/operations/docker/ci.dockerfile
    environment:
      - RUST_LOG=info
    entrypoint: >
      /bin/sh -c " sleep 2 && echo \"Launching insecure key-gen\" && simulator -f /app/config/local_centralized_from_compose.toml insecure-key-gen && echo \"Launching crs-gen\" && simulator -f /app/config/local_centralized_from_compose.toml insecure-crs-gen --max-num-bits 2048 && echo \"Success\" "
    volumes:
      - ../blockchain/simulator/config:/app/config
      - ../blockchain/gateway/.env:/app/.env.gateway

  # 6. Start gateway with key-id from key-gen
  # TODO: 
