name: zama-kms-s3-mock

services:
  # S3 mock
  dev-s3-mock:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: >
      minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 10s
      retries: 10

  # Minio client to create access keys
  dev-s3-mock-setup:
    image: quay.io/minio/mc
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ENDPOINT: "http://dev-s3-mock:9000"
    entrypoint: >
      /bin/sh -c "
      sleep 1 &&
      /usr/bin/mc alias set myminio $$MINIO_ENDPOINT ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      ACCESS_KEY=$$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1) &&
      SECRET_KEY=$$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 40 | head -n 1) &&
      /usr/bin/mc admin user add myminio $$ACCESS_KEY $$SECRET_KEY &&
      /usr/bin/mc admin policy attach myminio readwrite --user $$ACCESS_KEY &&
      echo '$ACCESS_KEY' &&
      echo '$SECRET_KEY' &&
      echo $$ACCESS_KEY > /minio_secrets/access_key &&
      echo $$SECRET_KEY > /minio_secrets/secret_key &&
      cat /minio_secrets/access_key &&
      cat /minio_secrets/secret_key &&
      mc mb --with-lock --ignore-existing myminio/kms &&
      mc anonymous set public myminio/kms
      "
    volumes:
      - minio_secrets:/minio_secrets
    depends_on:
      dev-s3-mock:
        condition: service_healthy

volumes:
  minio_secrets:
  validator_secrets:
