services:
  setup-fhevm-coprocessor-db:
    container_name: ${DOCKER_COMPOSE_PROJECT}-setup-fhevm-coprocessor-db
    image: ghcr.io/zama-ai/fhevm-db-migration:v0.1.2
    environment:
      DATABASE_URL: postgresql://postgres:postgres@${DOCKER_COMPOSE_PROJECT}-fhevm-coprocessor-db:5432/coprocessor
    volumes:
      - ../network-fhe-keys/:/fhevm-keys/
    networks:
      - zama_default

networks:
  zama_default:
    external: true
