services:
  db:
    image: postgres:15.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  coproc:
    image: ghcr.io/zama-ai/fhevm-coprocessor:v0.6.0
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coprocessor
    ports:
      - '50055:50052'
    volumes:
      - ../coprocessor.key:/usr/share/coprocessor.key
    command:
      - --run-bg-worker
      - --run-server
      - --server-addr=0.0.0.0:50052
      - --coprocessor-private-key=/usr/share/coprocessor.key
      - --worker-polling-interval-ms=500
  geth:
    image: ghcr.io/zama-ai/go-ethereum-coprocessor-dev:v0.1.2
    volumes:
      - ../blockchain/geth/entrypoint.sh:/entrypoint.sh
    environment:
      - FHEVM_COPROCESSOR_API_KEY=a1503fb6-d79b-4e9e-826d-44cf262f3e05
      - FHEVM_COPROCESSOR_URL=coproc:50052
      - COPROCESSOR_CONTRACT_ADDRESS=0x596E6682c72946AF006B27C131793F2b62527A4b
      - ACL_CONTRACT_ADDRESS=0x339EcE85B9E11a3A3AA557582784a15d7F82AAf2
      - FHEVM_COPROCESSOR_SYNC_INTERVAL=1s
    ports:
      - '8745:8545'
      - '8746:8546'
volumes:
  db:
    driver: local
