name: zama-kms-gateway

services:
  dev-kms-gateway:
    depends_on:
      dev-s3-mock-setup:
        condition: service_completed_successfully
    image: gw-with-integrated-kms:0.9.0-rc37
    ports:
      - "7077:7077"
    entrypoint: >
      /bin/sh -c "
      export AWS_ACCESS_KEY_ID=$$(cat /minio_secrets/access_key) &&
      export AWS_SECRET_ACCESS_KEY=$$(cat /minio_secrets/secret_key) &&
      gateway
      "
    volumes:
      - ../blockchain/gateway/config/connector.toml:/app/gateway/config/connector.toml
      - ../blockchain/gateway/config/gateway_centralized.toml:/app/gateway/config/gateway.toml
      - minio_secrets:/minio_secrets
      - ../core/service/config/compose_centralized.toml:/app/gateway/config/kms_core.toml
    environment:
      - RUST_BACKTRACE=1
