name: End-to-End test

on:
  push:
    branches:
      - ci/test-workflow
  workflow_dispatch:
    inputs:
      feature_branch:
        description: 'Feature branch to test (optional)'
        required: false
        default: 'main'

jobs:
  run-everything:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Verify Dependencies Installation
      run: |
        docker --version
        node --version

    - name: Check resources
      run: |
        free -h
        top -bn1 | grep "Cpu(s)"

    - name: Execute run-everything.sh
      id: run_script
      run: |
        cd ./coprocessor/
        ./scripts/run_everything.sh || true
        docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"

    - name: zama-kms-gateway-dev-kms-blockchain-asc-deploy-1
      run: |
        docker logs zama-kms-gateway-dev-kms-blockchain-asc-deploy-1

    - name: zama-kms-gateway-dev-kms-simulator-keygen-1
      run: |
        docker logs zama-kms-gateway-dev-kms-simulator-keygen-1

    - name: zama-kms-gateway-dev-kms-gateway-1
      run: |
        docker logs zama-kms-gateway-dev-kms-gateway-1

    - name: zama-kms-gateway-dev-kms-connector-1
      run: |
        docker logs zama-kms-gateway-dev-kms-connector-1

    - name: zama-kms-gateway-dev-kms-core-1
      run: |
        docker logs zama-kms-gateway-dev-kms-core-1

    - name: zama-kms-gateway-dev-kms-blockchain-validator-1
      run: |
        docker logs zama-kms-gateway-dev-kms-blockchain-validator-1

    - name: zama-kms-gateway-coproc-1
      run: |
        docker logs zama-kms-gateway-coproc-1

    - name: zama-kms-gateway-db-1
      run: |
        docker logs zama-kms-gateway-db-1

    - name: zama-kms-gateway-dev-s3-mock-1
      run: |
        docker logs zama-kms-gateway-dev-s3-mock-1

    - name: zama-kms-gateway-geth-1
      run: |
        docker logs zama-kms-gateway-geth-1

    - name: zama-kms-gateway-dev-kv-store-1
      run: |
        docker logs zama-kms-gateway-dev-kv-store-1
